network: 'LogisticRegression_TenBinaryClassifier_WithLasso_HOG'
multigpu: False
epochs: 50
batch_size: 128
num_workers: 8
learning_rate: 0.0001
weight_decay: 0
milestones: []
gamma: 0.1
print_frequency: 500
regularization: 1
lam: 0.00001
feature_extraction: hog