network: 'LinearModel_CrossEntropy_Ridge'
multigpu: False
epochs: 50
batch_size: 128
num_workers: 8
learning_rate: 0.0001
weight_decay: 0
milestones: []
gamma: 0.1
print_frequency: 50
regularization: 2
lam: 0.0001